# This file has been customized for a multi-app monorepo structure.

name: Deploy all apps to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Triggers deployment when code is merged into the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js environment (Essential for running build scripts)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Set to your project's Node version

      # Install all project dependencies once in the root folder
      - name: Install Root Dependencies
        run: npm ci

      # --- 1. BUILD & DEPLOY ADMIN DASHBOARD ---
      - name: Build Admin Dashboard
        # Run the build script specifically inside the admin-dashboard folder
        run: npm run build --prefix admin-dashboard 
      - name: Deploy Admin Dashboard
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          # Target name must match the "target" field in your firebase.json
          target: admin-dashboard 
          channelId: live

      # --- 2. BUILD & DEPLOY CONDUCTOR APP ---
      - name: Build Conductor App
        run: npm run build --prefix conductor-app
      - name: Deploy Conductor App
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: conductor-app
          channelId: live

      # --- 3. BUILD & DEPLOY STUDENT PORTAL ---
      - name: Build Student Portal
        run: npm run build --prefix student-portal
      - name: Deploy Student Portal
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: student-portal
          channelId: live