# This file is for deploying to a temporary PREVIEW channel on Pull Requests (PRs).
# The deployment creates a unique URL for review and cleanup automatically.

name: Deploy all apps to Firebase Hosting on PR

on:
  pull_request: # CORRECTED: Triggered when a Pull Request is opened, synced, or reopened
    types: [opened, synchronize, reopened]
    
jobs:
  build_and_preview: # Job name changed to reflect preview action
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    
    permissions: # Required for posting the preview URL back to the PR comments
      pull-requests: write 
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use your app's Node version

      - name: Install Root Dependencies
        run: npm ci

      # --- 1. BUILD & PREVIEW ADMIN DASHBOARD ---
      - name: Build Admin Dashboard
        run: npm ci --prefix admin-dashboard && npm run build --prefix admin-dashboard 
      - name: Deploy Admin Dashboard Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }} # Allows posting the URL to PR comments
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: admin-dashboard 
          # channelId is omitted: Deploying without a channelId creates a unique preview channel per PR/branch.

      # --- 2. BUILD & PREVIEW CONDUCTOR APP ---
      - name: Build Conductor App
        run: npm ci --prefix conductor-app && npm run build --prefix conductor-app
      - name: Deploy Conductor App Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: conductor-app

      # --- 3. BUILD & PREVIEW STUDENT PORTAL ---
      - name: Build Student Portal
        run: npm ci --prefix student-portal && npm run build --prefix student-portal
      - name: Deploy Student Portal Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: student-portal