# This file is for deploying to a temporary PREVIEW channel on Pull Requests (PRs).
#firebase-hosting-pull-request.yml
name: Deploy all apps to Firebase Hosting on PR

on:
  pull_request: # CORRECTED: Triggered when a Pull Request is opened or updated
    types: [opened, synchronize, reopened]
    
jobs:
  build_and_preview: # Job name changed to reflect preview action
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    
    permissions: # Required permissions for preview channels and commenting
      pull-requests: write 
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Root Dependencies
        run: npm ci

      # --- 1. BUILD & PREVIEW ADMIN DASHBOARD ---
      - name: Build Admin Dashboard
        run: npm ci --prefix admin-dashboard && npm run build --prefix admin-dashboard 
      - name: Deploy Admin Dashboard Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # Required to comment the preview URL back on the PR
          repoToken: ${{ secrets.GITHUB_TOKEN }} 
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: admin-dashboard 
          # Deploying to a unique preview channel (channelId is omitted for auto-generation)

      # --- 2. BUILD & PREVIEW CONDUCTOR APP ---
      - name: Build Conductor App
        run: npm ci --prefix conductor-app && npm run build --prefix conductor-app
      - name: Deploy Conductor App Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: conductor-app

      # --- 3. BUILD & PREVIEW STUDENT PORTAL ---
      - name: Build Student Portal
        run: npm ci --prefix student-portal && npm run build --prefix student-portal
      - name: Deploy Student Portal Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTPASS_APP_48365 }}
          projectId: smartpass-app-48365
          target: student-portal